export const GET_STARTERS = "GET_STARTERS";
export const STARTERS_LOADING = "STARTERS_LOADING";


export const GET_MAINS = "GET_MAINS";
export const MAINS_LOADING = "MAINS_LOADING";


export const GET_DESSERTS = "GET_DESSERTS";
export const DESSERTS_LOADING = "DESSERTS_LOADING";