export const GET_STARTERS = "GET_STARTERS";
export const STARTERS_LOADING = "STARTERS_LOADING";


export const GET_MAINS = "GET_MAINS";
export const MAINS_LOADING = "MAINS_LOADING";


export const GET_DESSERTS = "GET_DESSERTS";
export const DESSERTS_LOADING = "DESSERTS_LOADING";


export const GET_BOOKINGS = "GET_BOOKINGS";
export const ADD_BOOKING = "ADD_BOOKING";
export const BOOKINGS_LOADING = "BOOKINGS_LOADING";

export const GET_LUNCH_BOOKINGS = "GET_LUNCH_BOOKINGS";
export const ADD_LUNCH_BOOKING = "ADD_LUNCH_BOOKING";
export const LUNCH_BOOKINGS_LOADING = "LUNCH_BOOKINGS_LOADING";

export const GET_DINNER_BOOKINGS = "GET_DINNER_BOOKINGS";
export const ADD_DINNER_BOOKING = "ADD_DINNER_BOOKING";
export const DINNER_BOOKINGS_LOADING = "DINNER_BOOKINGS_LOADING";

export const ADD_REWARD = "ADD_REWARD"
export const GET_REWARDS = "GET_REWARDS"